val_tasks:
  - env_id: "maze"
    max_turns_per_episode: 9
    shortest_path_max_length: 8
    shortest_path_min_length: 7
    total_step_cap: 27
    test_size: 4
    inner_env_class: 'envs.maze_env_adapter.MazeEnvAdapter'
    shapes:  [[6,6],[7,6],[7,7],[6,7]]  

  - env_id: "game:Mastermind-v0-random"
    max_turns_per_episode: 3
    total_step_cap: 9
    code_length: 3
    num_numbers: 6
    duplicate_numbers: False
    test_size: 4
    inner_env_class: 'envs.gem_env_adapter.GEMEnvAdapter'